import { palette } from './palette'

export const fontHeading = '"Hammersmith One", sans-serif'
export const fontBody =
  '"proxima-nova", "Nunito Sans Variable", "Nunito Sans", "Helvetica Neue", Arial, sans-serif'

export const typography = {
  fontFamily: fontBody,
  h1: {
    fontFamily: fontHeading,
    fontSize: 'clamp(2.65rem, 1.2rem + 3vw, 4rem)',
    lineHeight: 1.08,
    fontWeight: 300,
    letterSpacing: '0.02em',
    textTransform: 'uppercase',
  },
  h2: {
    fontFamily: fontHeading,
    fontSize: 'clamp(2rem, 3vw, 3.3rem)',
    lineHeight: 1.08,
    letterSpacing: '0.01em',
    textTransform: 'uppercase',
  },
  h3: {
    fontFamily: fontBody,
    fontSize: 'clamp(1.5rem, 2vw, 2rem)',
    lineHeight: 1.12,
    letterSpacing: '0.035em',
    textTransform: 'uppercase',
  },
  h4: {
    fontFamily: fontHeading,
    fontSize: 'clamp(1.4rem, 1.4vw, 1.7rem)',
    letterSpacing: '0.03em',
    textTransform: 'uppercase',
  },
  editorialEmphasis: {
    fontFamily: fontBody,
    fontSize: 'clamp(1.4rem, 1.4vw, 1.7rem)',
    lineHeight: 1.2,
    fontWeight: 700,
    letterSpacing: '0.03em',
  },
  h5: {
    fontFamily: fontBody,
    fontSize: 'clamp(1rem, 0.7rem + 0.5vw, 1.05rem)',
    lineHeight: 1.2,
    fontWeight: 600,
    letterSpacing: '0.03em',
    textTransform: 'uppercase',
  },
  body1: { fontSize: 'clamp(1.08rem, 0.95rem + 0.35vw, 1.35rem)', lineHeight: 1.3 },
  bodyLarge: {
    fontSize: 'clamp(1.1875rem, 0.95rem + 0.5vw, 1.875rem)',
    lineHeight: 1.3,
  },
  body2: {
    fontSize: 'clamp(0.98rem, 0.9rem + 0.3vw, 1.2rem)',
    lineHeight: 1.25,
    color: palette.base[100],
  },
  caption: {
    fontSize: 'clamp(0.98rem, 0.85rem + 0.35vw, 1.15rem)',
    lineHeight: 1.2,
    color: palette.base[100],
  },
  button: {
    fontFamily: fontHeading,
    fontWeight: 300,
    letterSpacing: '0.08em',
    textTransform: 'uppercase',
    fontSize: '1.05rem',
    lineHeight: 1.2,
    '@media (max-width: 1919.95px)': { fontSize: '0.875rem', letterSpacing: '0.065em' },
    '@media (max-width: 1399.95px)': { fontSize: '0.8rem', letterSpacing: '0.055em' },
  },
  captionSmall: {
    fontFamily: fontBody,
    fontSize: 'clamp(0.9rem, 0.7rem + 0.16vw, 1.05rem)',
    lineHeight: 1.2,
    color: palette.base[100],
  },
  eyebrow: {
    fontFamily: fontHeading,
    fontSize: 'clamp(0.8rem, 0.82rem + 0.2vw, 1rem)',
    lineHeight: 1.2,
    letterSpacing: '0.22em',
    textTransform: 'uppercase',
    color: palette.brand.primaryGreen,
  },
  logo: {
    fontFamily: fontHeading,
    fontSize: 'clamp(1.2rem, 2vw, 2.1rem)',
    lineHeight: 1,
    fontWeight: 400,
    letterSpacing: '0.03em',
    textTransform: 'uppercase',
    color: palette.brand.primaryGreen,
  },
  logoHero: {
    fontFamily: fontHeading,
    fontSize: 'clamp(2rem, 1.2rem + 4vw, 4.7rem)',
    lineHeight: 0.95,
    fontWeight: 300,
    letterSpacing: '0.015em',
    textTransform: 'uppercase',
    color: palette.common.white,
  },
  cardTitle: { fontFamily: fontBody, fontSize: '1.2rem', lineHeight: 1.3, fontWeight: 700 },
  cardBody: { fontFamily: fontBody, fontSize: '1.02rem', lineHeight: 1.5 },
  meta: { fontFamily: fontBody, fontSize: '0.95rem', lineHeight: 1.3 },
  controlLabel: { fontFamily: fontBody, fontSize: '0.8125rem', lineHeight: 1.2 },
  navigationLabel: {
    fontFamily: fontBody,
    fontSize: 'clamp(1rem, 0.7rem + 0.5vw, 1.2rem)',
    fontWeight: 600,
    letterSpacing: '0.015em',
    lineHeight: 1.25,
  },
  displayNumber: {
    fontFamily: fontHeading,
    fontSize: 'clamp(3.5rem, 18vw, 8rem)',
    lineHeight: 0.9,
    letterSpacing: 0,
  },
  accentCardTitle: {
    fontFamily: fontBody,
    fontSize: 'clamp(1.15rem, 0.95rem + 0.65vw, 1.35rem)',
    fontWeight: 800,
    letterSpacing: 0,
    lineHeight: 1.05,
    textTransform: 'uppercase',
  },
  scenarioPanelTitle: {
    fontFamily: fontHeading,
    fontSize: 'clamp(0.72rem, 1.35vw, 1.35rem)',
    lineHeight: 1.08,
    textTransform: 'uppercase',
  },
  footerLogo: {
    fontFamily: fontHeading,
    fontSize: 'clamp(1.05rem, 1.4vw, 1.35rem)',
    lineHeight: 1.05,
    textTransform: 'uppercase',
  },
  // Dense chart labels for data-heavy internal visualizations.
  chartTitle: {
    fontFamily: fontHeading,
    fontSize: '1.1rem',
    lineHeight: 1.2,
    letterSpacing: '0.02em',
    textTransform: 'uppercase',
  },
  chartLabel: {
    fontFamily: fontBody,
    fontSize: '0.72rem',
    lineHeight: 1.15,
    fontWeight: 700,
    letterSpacing: '0.02em',
    textTransform: 'uppercase',
  },
  chartColumnHead: {
    fontFamily: fontBody,
    fontSize: '0.66rem',
    lineHeight: 1.2,
    letterSpacing: '0.06em',
    textTransform: 'uppercase',
    color: palette.base[100],
  },
  chartAxis: {
    fontFamily: fontBody,
    fontSize: '0.64rem',
    lineHeight: 1.2,
    color: palette.base[300],
  },
  chartValue: { fontFamily: fontHeading, fontSize: '0.9rem', lineHeight: 1 },
  chartValueLarge: { fontFamily: fontHeading, fontSize: '1.15rem', lineHeight: 1 },
  numberGhost: {
    fontFamily: fontHeading,
    fontSize: 'clamp(1.8rem, 1.4rem + 1vw, 2.2rem)',
    lineHeight: 1,
    letterSpacing: '0.04em',
    fontWeight: 400,
    textTransform: 'uppercase',
    color: palette.base[100],
  },
  numberArticle: {
    fontFamily: fontHeading,
    fontSize: 'clamp(0.95rem, 0.85rem + 0.3vw, 1.1rem)',
    lineHeight: 1,
    letterSpacing: '0.06em',
    fontWeight: 400,
    textTransform: 'uppercase',
    color: palette.brand.primaryGreen,
  },
  numberTimeline: {
    fontFamily: fontHeading,
    fontSize: 'clamp(2.2rem, 4vw, 3rem)',
    lineHeight: 1,
    letterSpacing: '0.04em',
    fontWeight: 400,
    textTransform: 'uppercase',
    color: palette.brand.primaryGreen,
  },
  numberBadge: {
    fontFamily: fontHeading,
    fontSize: 'clamp(0.8rem, 0.72rem + 0.2vw, 0.9rem)',
    lineHeight: 1,
    letterSpacing: '0.08em',
    fontWeight: 400,
    textTransform: 'uppercase',
    color: palette.brand.primaryGreen,
  },
} as const
